import type { CompanyProfile, EtfProfile } from "./schema.js";

// Redaktioneller Erstbestand. Wächst iterativ auf ~200 Unternehmen + 10 ETFs.
// Im Kindermodus werden KEINE frei generierten KI-Texte ausgespielt. ETFs sind neutrale
// Lernbeispiele, KEINE Kaufempfehlung. ISIN/WKN vor öffentlichem Start rechtlich verifizieren.

export const COMPANY_PROFILES: CompanyProfile[] = [
  {
    ticker: "AAPL",
    name: "Apple",
    whatDoes: "Apple entwickelt und verkauft Smartphones, Computer, Tablets, Uhren und Dienste.",
    howEarns: "Vor allem durch den Verkauf von Geräten wie dem iPhone und zusätzlich durch Dienste (z. B. App Store, iCloud).",
    products: "iPhone, iPad, Mac, Apple Watch, AirPods, App Store.",
    sector: "Technologie",
    competitors: "Samsung, Google, Microsoft.",
    opportunities: "Treue Kundschaft, starke Marke, wachsende Dienste-Umsätze.",
    risks: "Starke Abhängigkeit vom iPhone, Wettbewerb, Lieferketten in Asien.",
    whyPriceMoves: "Neue Produkte, Verkaufszahlen und die allgemeine Tech-Stimmung können den Kurs bewegen.",
  },
  {
    ticker: "SAP",
    name: "SAP",
    whatDoes: "SAP stellt Software her, mit der große Unternehmen ihre Abläufe (Einkauf, Personal, Finanzen) steuern.",
    howEarns: "Früher durch Software-Lizenzen, heute zunehmend durch Cloud-Abos (regelmäßige Mietzahlungen).",
    products: "Unternehmenssoftware (ERP), Cloud-Dienste.",
    sector: "Technologie",
    competitors: "Oracle, Microsoft, Salesforce.",
    opportunities: "Umstieg vieler Kunden in die Cloud, langfristige Verträge.",
    risks: "Harter Cloud-Wettbewerb, aufwendige Umstellungen bei Kunden.",
    whyPriceMoves: "Cloud-Wachstum, Quartalszahlen und Ausblicke beeinflussen den Kurs.",
  },
  {
    ticker: "SIE",
    name: "Siemens",
    whatDoes: "Siemens baut Technik für Industrie, Gebäude, Bahnverkehr und Stromnetze.",
    howEarns: "Durch Verkauf und Wartung von Maschinen, Anlagen, Zügen und Automatisierungstechnik.",
    products: "Industrieautomatisierung, Züge, Gebäudetechnik, Medizintechnik (Siemens Healthineers).",
    sector: "Industrie",
    competitors: "ABB, Schneider Electric, General Electric.",
    opportunities: "Automatisierung, Digitalisierung der Industrie, Bahn- und Energietrends.",
    risks: "Abhängigkeit von der Konjunktur, große langlaufende Projekte.",
    whyPriceMoves: "Auftragslage, Konjunktur und Großaufträge wirken auf den Kurs.",
  },
  {
    ticker: "NESN",
    name: "Nestlé",
    whatDoes: "Nestlé ist ein großer Lebensmittel- und Getränkekonzern aus der Schweiz.",
    howEarns: "Durch den Verkauf von Lebensmitteln und Getränken in vielen Ländern.",
    products: "Kaffee (Nescafé, Nespresso), Wasser, Süßwaren, Tiernahrung.",
    sector: "Konsumgüter",
    competitors: "Unilever, Mondelēz, Danone.",
    opportunities: "Bekannte Marken, weltweite Verbreitung, stabile Nachfrage nach Alltagsprodukten.",
    risks: "Rohstoffpreise, Wechselkurse, Diskussionen um Gesundheit und Nachhaltigkeit.",
    whyPriceMoves: "Absatzmengen, Preise und Wechselkurse können den Kurs bewegen.",
  },
  {
    ticker: "MSFT",
    name: "Microsoft",
    whatDoes: "Microsoft stellt Software und Cloud-Dienste für Menschen und Unternehmen her.",
    howEarns: "Durch Software (Windows, Office), Cloud (Azure) und Abos sowie Spiele (Xbox).",
    products: "Windows, Microsoft 365/Office, Azure, Xbox, Teams.",
    sector: "Technologie",
    competitors: "Google, Amazon, Apple.",
    opportunities: "Starkes Cloud-Geschäft, viele Firmenkunden, wachsende Abo-Umsätze.",
    risks: "Harter Cloud-Wettbewerb, Abhängigkeit von Firmenkunden, Regulierung.",
    whyPriceMoves: "Cloud-Wachstum, Quartalszahlen und die Tech-Stimmung bewegen den Kurs.",
  },
  {
    ticker: "AMZN",
    name: "Amazon",
    whatDoes: "Amazon betreibt einen riesigen Online-Handel und vermietet Cloud-Technik.",
    howEarns: "Durch Online-Verkäufe, Marktplatz-Gebühren, Abos (Prime) und die Cloud (AWS).",
    products: "Amazon-Onlineshop, Prime, AWS, Kindle, Alexa.",
    sector: "Konsum & Technologie",
    competitors: "Alibaba, Walmart, Microsoft (Cloud).",
    opportunities: "Wachstum im Online-Handel und in der Cloud, viele Prime-Mitglieder.",
    risks: "Niedrige Handelsmargen, hohe Kosten, Wettbewerb und Regulierung.",
    whyPriceMoves: "Wachstum von Handel und AWS sowie Gewinnentwicklung bewegen den Kurs.",
  },
  {
    ticker: "GOOGL",
    name: "Alphabet (Google)",
    whatDoes: "Alphabet ist das Mutterunternehmen von Google – Suche, YouTube, Android und mehr.",
    howEarns: "Vor allem durch Werbung in der Suche und auf YouTube, dazu Cloud-Dienste.",
    products: "Google-Suche, YouTube, Android, Chrome, Google Cloud.",
    sector: "Kommunikation/Technologie",
    competitors: "Microsoft, Meta, Amazon.",
    opportunities: "Sehr starke Werbeplattform, viele Nutzer, wachsende Cloud.",
    risks: "Abhängigkeit von Werbung, Datenschutz- und Wettbewerbsregeln.",
    whyPriceMoves: "Werbeeinnahmen, Nutzerzahlen und Regulierung bewegen den Kurs.",
  },
  {
    ticker: "NVDA",
    name: "Nvidia",
    whatDoes: "Nvidia entwickelt Chips für Grafik, Spiele und künstliche Intelligenz.",
    howEarns: "Durch den Verkauf von Grafik- und KI-Chips, vor allem an Rechenzentren.",
    products: "Grafikkarten (GeForce), KI-Beschleuniger für Rechenzentren.",
    sector: "Technologie",
    competitors: "AMD, Intel.",
    opportunities: "Großer Bedarf an KI-Chips, führende Technik.",
    risks: "Starke Schwankungen, Abhängigkeit vom KI-Boom, Wettbewerb, Lieferketten.",
    whyPriceMoves: "Nachfrage nach KI-Chips und Quartalszahlen bewegen den Kurs stark.",
  },
  {
    ticker: "TSLA",
    name: "Tesla",
    whatDoes: "Tesla baut Elektroautos und Speicher für Strom (Batterien).",
    howEarns: "Vor allem durch den Verkauf von Elektroautos, dazu Energie- und Softwareprodukte.",
    products: "Elektroautos (Model 3, Y), Batteriespeicher, Lade-Netzwerk.",
    sector: "Konsum/Auto",
    competitors: "Volkswagen, BYD, weitere Autohersteller.",
    opportunities: "Wachsender Markt für Elektroautos, bekannte Marke.",
    risks: "Starke Kursschwankungen, harter Wettbewerb, Abhängigkeit von wenigen Modellen.",
    whyPriceMoves: "Verkaufszahlen, Preise und Erwartungen bewegen den Kurs oft stark.",
  },
  {
    ticker: "VOW3",
    name: "Volkswagen",
    whatDoes: "Volkswagen ist ein großer Autohersteller mit vielen Marken.",
    howEarns: "Durch den Verkauf von Autos und Dienstleistungen rund ums Auto.",
    products: "VW, Audi, Porsche, Škoda, SEAT.",
    sector: "Konsum/Auto",
    competitors: "Toyota, Stellantis, Tesla.",
    opportunities: "Viele Marken, Umstieg auf Elektroautos, weltweite Präsenz.",
    risks: "Abhängigkeit von der Konjunktur, teurer Umbau zur E-Mobilität, Wettbewerb.",
    whyPriceMoves: "Absatzzahlen, Konjunktur und der E-Auto-Umstieg bewegen den Kurs.",
  },
  {
    ticker: "ALV",
    name: "Allianz",
    whatDoes: "Allianz ist ein großer Versicherungs- und Finanzkonzern.",
    howEarns: "Durch Versicherungsbeiträge und die Anlage/Verwaltung von Geld.",
    products: "Versicherungen (Auto, Leben, Sach), Vermögensverwaltung.",
    sector: "Finanzen",
    competitors: "AXA, Generali, Munich Re.",
    opportunities: "Stabile Beiträge, weltweites Geschäft, Vermögensverwaltung.",
    risks: "Große Schäden (z. B. Katastrophen), Zinsänderungen, Finanzmärkte.",
    whyPriceMoves: "Zinsen, Schadensereignisse und Finanzmärkte bewegen den Kurs.",
  },
  {
    ticker: "ADS",
    name: "Adidas",
    whatDoes: "Adidas stellt Sportschuhe, Kleidung und Ausrüstung her.",
    howEarns: "Durch den Verkauf von Sportartikeln über Handel und eigene Shops.",
    products: "Sportschuhe, Trikots, Sportkleidung.",
    sector: "Konsum",
    competitors: "Nike, Puma.",
    opportunities: "Starke Marke, weltweite Nachfrage, Sport-Trends.",
    risks: "Modetrends, Wettbewerb, Lieferketten und Wechselkurse.",
    whyPriceMoves: "Verkaufszahlen, Trends und Markenstärke bewegen den Kurs.",
  },
  {
    ticker: "MBG",
    name: "Mercedes-Benz Group",
    whatDoes: "Mercedes-Benz baut Autos und Transporter, vor allem in der Oberklasse.",
    howEarns: "Durch den Verkauf von Fahrzeugen und Finanzdienstleistungen.",
    products: "Pkw der Marke Mercedes-Benz, Vans, Finanzierung/Leasing.",
    sector: "Konsum/Auto",
    competitors: "BMW, Audi (VW), Tesla.",
    opportunities: "Starke Premium-Marke, Umstieg auf Elektro, weltweite Nachfrage.",
    risks: "Konjunktur, Wettbewerb, teurer E-Umbau, Wechselkurse.",
    whyPriceMoves: "Absatz in der Oberklasse, Konjunktur und E-Mobilität bewegen den Kurs.",
  },
  {
    ticker: "MC",
    name: "LVMH",
    whatDoes: "LVMH ist ein Luxuskonzern mit vielen bekannten Mode- und Marken.",
    howEarns: "Durch den Verkauf von Luxusgütern wie Mode, Taschen, Uhren und Parfüm.",
    products: "Louis Vuitton, Dior, Sephora, Champagner- und Uhrenmarken.",
    sector: "Konsum/Luxus",
    competitors: "Kering, Hermès, Richemont.",
    opportunities: "Starke Luxusmarken, treue Kundschaft, weltweites Wachstum.",
    risks: "Abhängigkeit von der Kauflaune Wohlhabender, Konjunktur, Wechselkurse.",
    whyPriceMoves: "Nachfrage nach Luxus, Konjunktur und Tourismus bewegen den Kurs.",
  },
  {
    ticker: "META",
    name: "Meta Platforms",
    whatDoes: "Meta betreibt soziale Netzwerke und Messenger, über die sich Menschen austauschen.",
    howEarns: "Fast ausschließlich durch Werbung, die zwischen den Inhalten angezeigt wird.",
    products: "Facebook, Instagram, WhatsApp, Messenger.",
    sector: "Kommunikation",
    competitors: "Google (YouTube), TikTok, Snap.",
    opportunities: "Sehr viele Nutzer weltweit, neue Funktionen und Videoformate.",
    risks: "Abhängigkeit vom Werbemarkt, Datenschutzregeln, junge Konkurrenz.",
    whyPriceMoves: "Nutzerzahlen, Werbeeinnahmen und Ausgaben für neue Projekte bewegen den Kurs.",
  },
  {
    ticker: "NFLX",
    name: "Netflix",
    whatDoes: "Netflix ist ein Streaming-Dienst für Filme und Serien.",
    howEarns: "Durch monatliche Abo-Gebühren der Zuschauer und zunehmend durch Werbe-Abos.",
    products: "Streaming-Abo, eigene Serien und Filme.",
    sector: "Medien",
    competitors: "Disney+, Amazon Prime Video, Apple TV+.",
    opportunities: "Weltweites Wachstum, eigene erfolgreiche Produktionen.",
    risks: "Starker Wettbewerb, hohe Produktionskosten, gesättigte Märkte.",
    whyPriceMoves: "Zahl neuer Abonnenten und Erfolg von Serien wirken auf den Kurs.",
  },
  {
    ticker: "DIS",
    name: "Walt Disney",
    whatDoes: "Disney macht Filme, betreibt Freizeitparks und Streaming-Dienste.",
    howEarns: "Durch Kino, Streaming-Abos, Freizeitparks und Verkauf von Produkten zu seinen Figuren.",
    products: "Disney+, Filmstudios (Marvel, Pixar, Star Wars), Disneyland.",
    sector: "Medien",
    competitors: "Netflix, Comcast, Warner Bros. Discovery.",
    opportunities: "Starke Marken und Figuren, viele Verwertungswege für eine Geschichte.",
    risks: "Teure Filmproduktionen, schwankende Park-Besuche, Streaming-Wettbewerb.",
    whyPriceMoves: "Kinoerfolge, Streaming-Zahlen und Park-Besucher beeinflussen den Kurs.",
  },
  {
    ticker: "KO",
    name: "Coca-Cola",
    whatDoes: "Coca-Cola stellt alkoholfreie Getränke her und verkauft sie weltweit.",
    howEarns: "Durch den Verkauf von Getränken und Sirup-Konzentraten an Abfüller und Händler.",
    products: "Coca-Cola, Fanta, Sprite, Wasser- und Saftmarken.",
    sector: "Konsumgüter",
    competitors: "PepsiCo, Nestlé, regionale Getränkehersteller.",
    opportunities: "Sehr bekannte Marken, weltweite Verbreitung, stabile Nachfrage.",
    risks: "Gesundheitstrends weg von Zucker, Rohstoff- und Wechselkurse.",
    whyPriceMoves: "Absatzmengen, Preise und Wechselkurse können den Kurs bewegen.",
  },
  {
    ticker: "PEP",
    name: "PepsiCo",
    whatDoes: "PepsiCo stellt Getränke und Snacks her.",
    howEarns: "Durch den Verkauf von Getränken und Knabbereien in vielen Ländern.",
    products: "Pepsi, Lay’s/Chips, Gatorade, Quaker.",
    sector: "Konsumgüter",
    competitors: "Coca-Cola, Mondelēz, Nestlé.",
    opportunities: "Breites Sortiment aus Snacks und Getränken, bekannte Marken.",
    risks: "Gesundheitstrends, Rohstoffpreise, Wechselkurse.",
    whyPriceMoves: "Verkaufsmengen und Preise der Marken wirken auf den Kurs.",
  },
  {
    ticker: "MCD",
    name: "McDonald’s",
    whatDoes: "McDonald’s betreibt und vergibt Schnellrestaurants weltweit.",
    howEarns: "Durch eigene Restaurants und Gebühren von Franchise-Partnern, die die Marke nutzen.",
    products: "Burger, Pommes, Getränke, Frühstück.",
    sector: "Konsum",
    competitors: "Burger King, KFC, lokale Restaurantketten.",
    opportunities: "Bekannte Marke, viele Standorte, Liefer- und Digitalangebote.",
    risks: "Gesundheitsdebatten, Lohn- und Rohstoffkosten, Wettbewerb.",
    whyPriceMoves: "Umsatz je Restaurant und Zahl der Standorte beeinflussen den Kurs.",
  },
  {
    ticker: "SBUX",
    name: "Starbucks",
    whatDoes: "Starbucks betreibt eine weltweite Kette von Kaffeehäusern.",
    howEarns: "Durch den Verkauf von Kaffee, Getränken und Snacks in seinen Filialen.",
    products: "Kaffeespezialitäten, Tee, Snacks, eigene App.",
    sector: "Konsum",
    competitors: "Lokale Cafés, Bäckereiketten, Schnellrestaurants mit Kaffee.",
    opportunities: "Starke Marke, Treueprogramm, Wachstum in Asien.",
    risks: "Kaffeepreise, Konjunktur, starker lokaler Wettbewerb.",
    whyPriceMoves: "Besucherzahlen und Umsatz je Filiale wirken auf den Kurs.",
  },
  {
    ticker: "NKE",
    name: "Nike",
    whatDoes: "Nike entwirft und verkauft Sportschuhe und Sportkleidung.",
    howEarns: "Durch den Verkauf seiner Produkte im Handel und über eigene Shops und Apps.",
    products: "Sportschuhe, Sportbekleidung, Zubehör.",
    sector: "Konsum",
    competitors: "Adidas, Puma, New Balance.",
    opportunities: "Starke Marke, Sport-Sponsoring, direkter Onlineverkauf.",
    risks: "Modetrends, Lieferketten in Asien, Wettbewerb.",
    whyPriceMoves: "Verkaufszahlen, Lagerbestände und Modetrends bewegen den Kurs.",
  },
  {
    ticker: "V",
    name: "Visa",
    whatDoes: "Visa betreibt ein Netzwerk, über das Kartenzahlungen abgewickelt werden.",
    howEarns: "Durch kleine Gebühren für jede Zahlung, die über das Netzwerk läuft.",
    products: "Zahlungsnetzwerk für Kredit- und Debitkarten.",
    sector: "Finanzdienstleistung",
    competitors: "Mastercard, PayPal, neue Bezahldienste.",
    opportunities: "Weltweiter Trend weg vom Bargeld, mehr digitale Zahlungen.",
    risks: "Regulierung der Gebühren, neue Bezahlmethoden, Konjunktur.",
    whyPriceMoves: "Zahl und Höhe der Zahlungen weltweit beeinflussen den Kurs.",
  },
  {
    ticker: "MA",
    name: "Mastercard",
    whatDoes: "Mastercard betreibt wie Visa ein Netzwerk für Kartenzahlungen.",
    howEarns: "Durch Gebühren für Zahlungen, die über das Netzwerk abgewickelt werden.",
    products: "Zahlungsnetzwerk, Sicherheits- und Datendienste.",
    sector: "Finanzdienstleistung",
    competitors: "Visa, PayPal, neue Bezahldienste.",
    opportunities: "Mehr digitale Zahlungen weltweit, neue Dienste rund ums Bezahlen.",
    risks: "Regulierung, neue Konkurrenz, Konjunktur.",
    whyPriceMoves: "Weltweites Zahlungsvolumen und neue Dienste wirken auf den Kurs.",
  },
  {
    ticker: "PYPL",
    name: "PayPal",
    whatDoes: "PayPal bietet Online-Bezahldienste für Käufer und Händler.",
    howEarns: "Durch Gebühren für Zahlungen, die über die Dienste laufen.",
    products: "PayPal-Konto, Bezahlbutton für Shops, Geldtransfer.",
    sector: "Finanzdienstleistung",
    competitors: "Visa, Mastercard, Apple Pay, Klarna.",
    opportunities: "Wachsender Onlinehandel, viele bestehende Konten.",
    risks: "Starker Wettbewerb, Margendruck, Regulierung.",
    whyPriceMoves: "Zahl der Zahlungen und aktiven Konten beeinflusst den Kurs.",
  },
  {
    ticker: "INTC",
    name: "Intel",
    whatDoes: "Intel entwickelt und fertigt Computerchips, vor allem Prozessoren.",
    howEarns: "Durch den Verkauf von Chips für Computer, Rechenzentren und Geräte.",
    products: "Prozessoren für PCs und Server, Chip-Fertigung.",
    sector: "Technologie",
    competitors: "AMD, Nvidia, TSMC.",
    opportunities: "Hoher Chipbedarf, eigener Ausbau der Fertigung.",
    risks: "Starker Wettbewerb, teure Fabriken, schneller Technikwandel.",
    whyPriceMoves: "Nachfrage nach Chips und Fortschritte in der Fertigung bewegen den Kurs.",
  },
  {
    ticker: "AMD",
    name: "AMD",
    whatDoes: "AMD entwickelt Prozessoren und Grafikchips für Computer.",
    howEarns: "Durch den Verkauf von Chips an Hersteller von Computern und Rechenzentren.",
    products: "Prozessoren, Grafikkarten-Chips, Chips für Spielkonsolen.",
    sector: "Technologie",
    competitors: "Intel, Nvidia.",
    opportunities: "Wachsender Bedarf für Spiele, KI und Rechenzentren.",
    risks: "Abhängigkeit von Auftragsfertigern, harter Wettbewerb.",
    whyPriceMoves: "Nachfrage nach leistungsfähigen Chips und neue Modelle wirken auf den Kurs.",
  },
  {
    ticker: "ORCL",
    name: "Oracle",
    whatDoes: "Oracle stellt Datenbank- und Unternehmenssoftware sowie Cloud-Dienste her.",
    howEarns: "Durch Software-Lizenzen und zunehmend durch Cloud-Abos.",
    products: "Datenbanken, Unternehmenssoftware, Cloud-Infrastruktur.",
    sector: "Technologie",
    competitors: "SAP, Microsoft, Amazon (Cloud).",
    opportunities: "Umstieg vieler Kunden in die Cloud, langfristige Verträge.",
    risks: "Cloud-Wettbewerb, aufwendige Umstellungen bei Kunden.",
    whyPriceMoves: "Cloud-Wachstum und Quartalszahlen beeinflussen den Kurs.",
  },
  {
    ticker: "UBER",
    name: "Uber",
    whatDoes: "Uber vermittelt über eine App Fahrten und Essenslieferungen.",
    howEarns: "Durch einen Anteil an jeder vermittelten Fahrt und Lieferung.",
    products: "Fahrdienst-App, Essenslieferung (Uber Eats).",
    sector: "Technologie",
    competitors: "Lokale Fahrdienste, Lieferando, Bolt.",
    opportunities: "Wachsende Nutzung von App-Diensten, neue Angebote.",
    risks: "Regulierung, Wettbewerb, Rechte der Fahrerinnen und Fahrer.",
    whyPriceMoves: "Zahl der Fahrten und Lieferungen sowie die Kostenlage wirken auf den Kurs.",
  },
  {
    ticker: "ABNB",
    name: "Airbnb",
    whatDoes: "Airbnb vermittelt über eine Plattform Unterkünfte zwischen Gastgebern und Gästen.",
    howEarns: "Durch Gebühren für jede vermittelte Buchung.",
    products: "Buchungsplattform für Unterkünfte und Erlebnisse.",
    sector: "Technologie",
    competitors: "Booking, Hotelketten, andere Buchungsportale.",
    opportunities: "Beliebtheit von Reisen, viele angebotene Unterkünfte.",
    risks: "Regeln für Kurzzeitvermietung, Konjunktur, Wettbewerb.",
    whyPriceMoves: "Zahl der Buchungen und Reisetrends beeinflussen den Kurs.",
  },
  {
    ticker: "BMW",
    name: "BMW",
    whatDoes: "BMW baut Autos und Motorräder im gehobenen Bereich.",
    howEarns: "Durch den Verkauf von Fahrzeugen, Finanzierung und Service.",
    products: "Pkw der Marken BMW, MINI und Rolls-Royce, Motorräder.",
    sector: "Automobil",
    competitors: "Mercedes-Benz, Audi (VW), Tesla.",
    opportunities: "Elektroautos, starke Marke, weltweiter Absatz.",
    risks: "Hohe Entwicklungskosten, Konjunktur, Wettbewerb bei E-Autos.",
    whyPriceMoves: "Absatzzahlen, Konjunktur und Fortschritt bei E-Autos bewegen den Kurs.",
  },
  {
    ticker: "P911",
    name: "Porsche AG",
    whatDoes: "Porsche baut hochwertige Sportwagen.",
    howEarns: "Durch den Verkauf von Fahrzeugen sowie Service und Zubehör.",
    products: "Sportwagen wie 911, Taycan und SUV-Modelle.",
    sector: "Automobil",
    competitors: "Ferrari, Mercedes-Benz, BMW.",
    opportunities: "Starke Marke, hohe Margen, Elektromodelle.",
    risks: "Abhängigkeit von der Konjunktur im Luxussegment, Wettbewerb.",
    whyPriceMoves: "Absatz im Premiumbereich und Modellzyklen wirken auf den Kurs.",
  },
  {
    ticker: "DTE",
    name: "Deutsche Telekom",
    whatDoes: "Die Deutsche Telekom bietet Mobilfunk, Internet und Festnetz an.",
    howEarns: "Durch monatliche Gebühren für Handy- und Internetverträge.",
    products: "Mobilfunk, Internet, Festnetz, Telekom-/T-Mobile-Marken.",
    sector: "Kommunikation",
    competitors: "Vodafone, Telefónica, regionale Anbieter.",
    opportunities: "Großes US-Geschäft (T-Mobile), Ausbau schneller Netze.",
    risks: "Hohe Kosten für Netzausbau, Wettbewerb, Regulierung.",
    whyPriceMoves: "Kundenzahlen und Investitionen in die Netze beeinflussen den Kurs.",
  },
  {
    ticker: "BAS",
    name: "BASF",
    whatDoes: "BASF ist ein großer Chemiekonzern und stellt Grundstoffe für viele Branchen her.",
    howEarns: "Durch den Verkauf von Chemieprodukten an Industrie und Landwirtschaft.",
    products: "Kunststoffe, Lacke, Pflanzenschutz, Grundchemikalien.",
    sector: "Chemie",
    competitors: "Dow, Bayer, Covestro.",
    opportunities: "Breites Produktsortiment, viele Abnehmerbranchen.",
    risks: "Energiekosten, Konjunktur, strenge Umweltauflagen.",
    whyPriceMoves: "Konjunktur, Energiepreise und Nachfrage der Industrie wirken auf den Kurs.",
  },
  {
    ticker: "BAYN",
    name: "Bayer",
    whatDoes: "Bayer ist ein Konzern für Arzneimittel, Gesundheitsprodukte und Agrarprodukte.",
    howEarns: "Durch den Verkauf von Medikamenten, rezeptfreien Produkten und Saatgut/Pflanzenschutz.",
    products: "Medikamente, Aspirin, Saatgut und Pflanzenschutz.",
    sector: "Pharma",
    competitors: "Novartis, Roche, BASF (Agrar).",
    opportunities: "Forschung an neuen Medikamenten, weltweite Nachfrage.",
    risks: "Lange teure Forschung, Patentabläufe, Rechtsstreitigkeiten.",
    whyPriceMoves: "Erfolge in der Forschung und rechtliche Themen bewegen den Kurs.",
  },
  {
    ticker: "PUM",
    name: "Puma",
    whatDoes: "Puma entwirft und verkauft Sportschuhe und Sportkleidung.",
    howEarns: "Durch den Verkauf seiner Produkte im Handel und über eigene Kanäle.",
    products: "Sportschuhe, Sportbekleidung, Zubehör.",
    sector: "Konsum",
    competitors: "Nike, Adidas, New Balance.",
    opportunities: "Wachsende Marke, Sport-Sponsoring, Onlineverkauf.",
    risks: "Modetrends, Lieferketten, starker Wettbewerb.",
    whyPriceMoves: "Verkaufszahlen und Modetrends beeinflussen den Kurs.",
  },
  {
    ticker: "ZAL",
    name: "Zalando",
    whatDoes: "Zalando betreibt einen großen Online-Shop für Mode in Europa.",
    howEarns: "Durch den Verkauf von Kleidung und Schuhen sowie Gebühren von Partner-Marken.",
    products: "Online-Modeplattform, eigene App.",
    sector: "Konsum",
    competitors: "Amazon, About You, lokale Modehändler.",
    opportunities: "Wachsender Onlinehandel mit Mode in Europa.",
    risks: "Retouren, harter Wettbewerb, schwankende Kauflaune.",
    whyPriceMoves: "Bestellmengen und Gewinnmargen wirken auf den Kurs.",
  },
  {
    ticker: "RACE",
    name: "Ferrari",
    whatDoes: "Ferrari baut sehr hochwertige Sportwagen in kleiner Stückzahl.",
    howEarns: "Durch den Verkauf von Sportwagen sowie Lizenzen und Merchandising.",
    products: "Luxus-Sportwagen, Zubehör, Markenprodukte.",
    sector: "Automobil",
    competitors: "Porsche, Lamborghini, Aston Martin.",
    opportunities: "Sehr starke Marke, hohe Margen, lange Wartelisten.",
    risks: "Abhängigkeit vom Luxussegment, Umstieg auf E-Antrieb.",
    whyPriceMoves: "Auslieferungen und die Marke im Luxusbereich wirken auf den Kurs.",
  },
  {
    ticker: "AIR",
    name: "Airbus",
    whatDoes: "Airbus baut Verkehrsflugzeuge, Hubschrauber und Raumfahrttechnik.",
    howEarns: "Vor allem durch den Verkauf von Flugzeugen an Fluggesellschaften.",
    products: "Verkehrsflugzeuge, Hubschrauber, Satelliten.",
    sector: "Luftfahrt",
    competitors: "Boeing, Embraer.",
    opportunities: "Hohe Nachfrage nach Flugzeugen, langer Auftragsbestand.",
    risks: "Lieferketten, lange Bauzeiten, Konjunktur im Luftverkehr.",
    whyPriceMoves: "Bestellungen und Auslieferungen von Flugzeugen bewegen den Kurs.",
  },
  {
    ticker: "ASML",
    name: "ASML",
    whatDoes: "ASML baut Maschinen, mit denen moderne Computerchips hergestellt werden.",
    howEarns: "Durch den Verkauf und die Wartung dieser Maschinen an Chip-Hersteller.",
    products: "Belichtungsmaschinen für die Chip-Fertigung.",
    sector: "Technologie",
    competitors: "Nur wenige; in der Spitzentechnik kaum direkte Konkurrenz.",
    opportunities: "Wachsender Chipbedarf, technischer Vorsprung.",
    risks: "Wenige Großkunden, Exportregeln, schwankende Chip-Nachfrage.",
    whyPriceMoves: "Bestellungen der Chip-Hersteller und Exportregeln wirken auf den Kurs.",
  },
  {
    ticker: "JPM",
    name: "JPMorgan Chase",
    whatDoes: "JPMorgan Chase ist eine sehr große US-Bank für Privatkunden und Unternehmen.",
    howEarns: "Durch Zinsen auf Kredite, Gebühren und Geschäfte an den Finanzmärkten.",
    products: "Konten, Kredite, Kreditkarten, Vermögensverwaltung, Investmentbanking.",
    sector: "Finanzdienstleistung",
    competitors: "Bank of America, Citigroup, Goldman Sachs.",
    opportunities: "Große Kundenbasis, viele Geschäftsfelder, Stärke in Krisen.",
    risks: "Konjunktur und Zinsen, Kreditausfälle, strenge Regulierung.",
    whyPriceMoves: "Zinsen, Konjunktur und Kreditausfälle bewegen den Kurs.",
  },
  {
    ticker: "WMT",
    name: "Walmart",
    whatDoes: "Walmart betreibt sehr große Einzelhandelsmärkte und einen Onlineshop.",
    howEarns: "Durch den Verkauf von Lebensmitteln und Waren in Märkten und online.",
    products: "Supermärkte, Onlinehandel, Eigenmarken.",
    sector: "Konsumgüter",
    competitors: "Amazon, Costco, Target.",
    opportunities: "Riesige Reichweite, niedrige Preise, wachsendes Onlinegeschäft.",
    risks: "Geringe Margen, harter Preiswettbewerb, Lohnkosten.",
    whyPriceMoves: "Umsatz je Markt und Onlinewachstum wirken auf den Kurs.",
  },
  {
    ticker: "HD",
    name: "Home Depot",
    whatDoes: "Home Depot ist eine große US-Baumarktkette.",
    howEarns: "Durch den Verkauf von Werkzeug, Baustoffen und Heimwerkerbedarf.",
    products: "Baumärkte, Werkzeug, Baumaterial, Garten.",
    sector: "Konsum",
    competitors: "Lowe’s, lokale Baumärkte.",
    opportunities: "Heimwerker- und Bautrends, Profikunden, Onlineverkauf.",
    risks: "Abhängigkeit vom Wohnungsmarkt und der Konjunktur.",
    whyPriceMoves: "Bau- und Renovierungsnachfrage beeinflusst den Kurs.",
  },
  {
    ticker: "COST",
    name: "Costco",
    whatDoes: "Costco betreibt Großmärkte, in denen Mitglieder günstig in großen Mengen einkaufen.",
    howEarns: "Durch Warenverkauf und vor allem durch jährliche Mitgliedsbeiträge.",
    products: "Großmärkte, Eigenmarke, Mitgliedschaft.",
    sector: "Konsumgüter",
    competitors: "Walmart, Amazon, lokale Großhändler.",
    opportunities: "Treue Mitglieder, planbare Beiträge, niedrige Preise.",
    risks: "Geringe Margen, Abhängigkeit von Mitgliederzahlen.",
    whyPriceMoves: "Mitgliederzahl und Umsatz je Markt wirken auf den Kurs.",
  },
  {
    ticker: "PG",
    name: "Procter & Gamble",
    whatDoes: "Procter & Gamble stellt Produkte für Haushalt und Körperpflege her.",
    howEarns: "Durch den Verkauf von Alltagsprodukten in vielen Ländern.",
    products: "Pflege-, Wasch- und Haushaltsmarken.",
    sector: "Konsumgüter",
    competitors: "Unilever, Henkel, Beiersdorf.",
    opportunities: "Bekannte Marken, stabile Nachfrage nach Alltagsprodukten.",
    risks: "Rohstoffpreise, Wechselkurse, Eigenmarken der Händler.",
    whyPriceMoves: "Absatzmengen und Preise der Marken bewegen den Kurs.",
  },
  {
    ticker: "JNJ",
    name: "Johnson & Johnson",
    whatDoes: "Johnson & Johnson entwickelt Medikamente und Medizinprodukte.",
    howEarns: "Durch den Verkauf von Arzneimitteln und medizinischen Geräten.",
    products: "Medikamente, Medizintechnik, Gesundheitsprodukte.",
    sector: "Gesundheit",
    competitors: "Pfizer, Roche, Novartis.",
    opportunities: "Forschung an neuen Medikamenten, alternde Bevölkerung.",
    risks: "Lange teure Forschung, Patentabläufe, Rechtsstreitigkeiten.",
    whyPriceMoves: "Forschungserfolge und rechtliche Themen wirken auf den Kurs.",
  },
  {
    ticker: "PFE",
    name: "Pfizer",
    whatDoes: "Pfizer ist ein großer Hersteller von Medikamenten und Impfstoffen.",
    howEarns: "Durch den Verkauf von verschreibungspflichtigen Medikamenten und Impfstoffen.",
    products: "Medikamente, Impfstoffe.",
    sector: "Gesundheit",
    competitors: "Johnson & Johnson, Novartis, Roche.",
    opportunities: "Neue Wirkstoffe, weltweite Nachfrage nach Gesundheit.",
    risks: "Patentabläufe, schwankende Nachfrage, teure Forschung.",
    whyPriceMoves: "Erfolg neuer Medikamente und Patentabläufe bewegen den Kurs.",
  },
  {
    ticker: "LLY",
    name: "Eli Lilly",
    whatDoes: "Eli Lilly ist ein Pharmakonzern, bekannt u. a. für Mittel gegen Diabetes.",
    howEarns: "Durch den Verkauf verschreibungspflichtiger Medikamente.",
    products: "Medikamente gegen Diabetes und weitere Krankheiten.",
    sector: "Gesundheit",
    competitors: "Novo Nordisk, Pfizer, Johnson & Johnson.",
    opportunities: "Große Nachfrage nach neuen Therapien.",
    risks: "Abhängigkeit von einzelnen Medikamenten, Patentabläufe.",
    whyPriceMoves: "Erfolg wichtiger Medikamente beeinflusst den Kurs.",
  },
  {
    ticker: "XOM",
    name: "Exxon Mobil",
    whatDoes: "Exxon Mobil fördert und verarbeitet Öl und Gas.",
    howEarns: "Durch Förderung, Verarbeitung und Verkauf von Öl-, Gas- und Chemieprodukten.",
    products: "Kraftstoffe, Schmierstoffe, Chemieprodukte.",
    sector: "Energie",
    competitors: "Chevron, Shell, TotalEnergies.",
    opportunities: "Weltweiter Energiebedarf, Investitionen in neue Felder.",
    risks: "Schwankende Öl-/Gaspreise, Klimaregeln, Umstieg auf saubere Energie.",
    whyPriceMoves: "Vor allem der Öl- und Gaspreis bewegt den Kurs.",
  },
  {
    ticker: "CVX",
    name: "Chevron",
    whatDoes: "Chevron ist ein großer Öl- und Gaskonzern.",
    howEarns: "Durch Förderung, Verarbeitung und Verkauf von Öl- und Gasprodukten.",
    products: "Kraftstoffe, Schmierstoffe, Gas.",
    sector: "Energie",
    competitors: "Exxon Mobil, Shell, BP.",
    opportunities: "Energiebedarf weltweit, stabile Großprojekte.",
    risks: "Schwankende Energiepreise, Klimaregeln, hohe Investitionen.",
    whyPriceMoves: "Öl- und Gaspreise sowie Fördermengen wirken auf den Kurs.",
  },
  {
    ticker: "BA",
    name: "Boeing",
    whatDoes: "Boeing baut Verkehrsflugzeuge sowie Technik für Verteidigung und Raumfahrt.",
    howEarns: "Vor allem durch den Verkauf von Flugzeugen an Fluggesellschaften.",
    products: "Verkehrsflugzeuge, Verteidigungs- und Raumfahrttechnik.",
    sector: "Industrie",
    competitors: "Airbus, Embraer.",
    opportunities: "Hohe Nachfrage nach Flugzeugen, langer Auftragsbestand.",
    risks: "Qualitäts- und Sicherheitsthemen, Lieferketten, lange Bauzeiten.",
    whyPriceMoves: "Bestellungen, Auslieferungen und Sicherheitsthemen bewegen den Kurs.",
  },
  {
    ticker: "CAT",
    name: "Caterpillar",
    whatDoes: "Caterpillar baut Bau- und Bergbaumaschinen.",
    howEarns: "Durch Verkauf, Vermietung und Wartung von Maschinen.",
    products: "Bagger, Bulldozer, Motoren, Bergbaufahrzeuge.",
    sector: "Industrie",
    competitors: "Komatsu, Deere, Volvo.",
    opportunities: "Bau- und Infrastrukturprojekte weltweit.",
    risks: "Stark von der Konjunktur abhängig, Rohstoffpreise.",
    whyPriceMoves: "Bau- und Bergbaukonjunktur beeinflusst den Kurs.",
  },
  {
    ticker: "CRM",
    name: "Salesforce",
    whatDoes: "Salesforce bietet Software, mit der Unternehmen ihre Kundenbeziehungen verwalten.",
    howEarns: "Durch Cloud-Abos für seine Software.",
    products: "Kundenmanagement-Software (CRM), Cloud-Dienste.",
    sector: "Technologie",
    competitors: "Microsoft, SAP, Oracle.",
    opportunities: "Wachsender Bedarf an Cloud-Software, Zusatzdienste.",
    risks: "Starker Wettbewerb, Konjunktur bei Firmenkunden.",
    whyPriceMoves: "Abo-Wachstum und Quartalszahlen wirken auf den Kurs.",
  },
  {
    ticker: "ADBE",
    name: "Adobe",
    whatDoes: "Adobe stellt Software für Design, Fotos, Videos und Dokumente her.",
    howEarns: "Durch monatliche Abos für seine Programme.",
    products: "Photoshop, Acrobat/PDF, Video- und Designprogramme.",
    sector: "Technologie",
    competitors: "Canva, Microsoft, kleinere Spezialanbieter.",
    opportunities: "Kreativ- und KI-Funktionen, stabile Abo-Einnahmen.",
    risks: "Neue günstige Konkurrenz, Konjunktur.",
    whyPriceMoves: "Abo-Wachstum und neue Funktionen beeinflussen den Kurs.",
  },
  {
    ticker: "AVGO",
    name: "Broadcom",
    whatDoes: "Broadcom entwickelt Chips und Software für Netzwerke und Rechenzentren.",
    howEarns: "Durch den Verkauf von Chips und Unternehmenssoftware.",
    products: "Netzwerk- und Funkchips, Infrastruktursoftware.",
    sector: "Technologie",
    competitors: "Qualcomm, Nvidia, Marvell.",
    opportunities: "Hoher Bedarf durch KI und Rechenzentren.",
    risks: "Wenige Großkunden, schwankende Chip-Nachfrage.",
    whyPriceMoves: "Chip-Nachfrage und große Aufträge bewegen den Kurs.",
  },
  {
    ticker: "CSCO",
    name: "Cisco",
    whatDoes: "Cisco baut Technik, mit der Computernetzwerke und das Internet funktionieren.",
    howEarns: "Durch Verkauf von Netzwerktechnik sowie Software und Service.",
    products: "Router, Switches, Netzwerk- und Sicherheitssoftware.",
    sector: "Technologie",
    competitors: "Huawei, Juniper, Arista.",
    opportunities: "Netzausbau, Sicherheit und Cloud-Vernetzung.",
    risks: "Wettbewerb, Wandel hin zu Software, Konjunktur.",
    whyPriceMoves: "Nachfrage nach Netzwerktechnik wirkt auf den Kurs.",
  },
  {
    ticker: "QCOM",
    name: "Qualcomm",
    whatDoes: "Qualcomm entwickelt Chips und Funktechnik, vor allem für Smartphones.",
    howEarns: "Durch den Verkauf von Chips und durch Lizenzgebühren für Technik.",
    products: "Smartphone-Chips, Mobilfunktechnik, Lizenzen.",
    sector: "Technologie",
    competitors: "MediaTek, Apple (eigene Chips), Samsung.",
    opportunities: "5G, vernetzte Geräte, Chips fürs Auto.",
    risks: "Abhängigkeit vom Smartphone-Markt, Streit um Lizenzen.",
    whyPriceMoves: "Smartphone-Nachfrage und Lizenzeinnahmen bewegen den Kurs.",
  },
  {
    ticker: "SPOT",
    name: "Spotify",
    whatDoes: "Spotify ist ein Streaming-Dienst für Musik und Podcasts.",
    howEarns: "Durch Abo-Gebühren und durch Werbung im kostenlosen Angebot.",
    products: "Musik- und Podcast-Streaming, App.",
    sector: "Medien",
    competitors: "Apple Music, Amazon Music, YouTube.",
    opportunities: "Weltweites Wachstum, mehr zahlende Abonnenten.",
    risks: "Hohe Abgaben an Musikfirmen, starker Wettbewerb.",
    whyPriceMoves: "Zahl der Abonnenten und die Margen wirken auf den Kurs.",
  },
  {
    ticker: "SHOP",
    name: "Shopify",
    whatDoes: "Shopify stellt Software bereit, mit der Händler eigene Onlineshops betreiben.",
    howEarns: "Durch Abos und durch Gebühren für Zahlungen und Zusatzdienste.",
    products: "Shopsystem, Bezahl- und Versanddienste.",
    sector: "Technologie",
    competitors: "Amazon, WooCommerce, große Shopanbieter.",
    opportunities: "Wachsender Onlinehandel, viele kleine Händler.",
    risks: "Abhängigkeit von der Konjunktur kleiner Händler, Wettbewerb.",
    whyPriceMoves: "Umsatz der Händler und neue Dienste beeinflussen den Kurs.",
  },
  {
    ticker: "BABA",
    name: "Alibaba",
    whatDoes: "Alibaba betreibt große Online-Handelsplätze und Cloud-Dienste in Asien.",
    howEarns: "Durch Gebühren und Werbung im Onlinehandel sowie Cloud-Dienste.",
    products: "Online-Marktplätze, Cloud, Bezahldienste.",
    sector: "Konsum",
    competitors: "Amazon, JD.com, Tencent.",
    opportunities: "Großer Markt in Asien, wachsende Cloud-Sparte.",
    risks: "Regulierung in China, Wettbewerb, politische Unsicherheit.",
    whyPriceMoves: "Handelsvolumen und politische/regulatorische Themen bewegen den Kurs.",
  },
  {
    ticker: "DBK",
    name: "Deutsche Bank",
    whatDoes: "Die Deutsche Bank ist Deutschlands größte Bank für Privat- und Firmenkunden.",
    howEarns: "Durch Zinsen, Gebühren und Geschäfte an den Finanzmärkten.",
    products: "Konten, Kredite, Vermögensverwaltung, Investmentbanking.",
    sector: "Finanzdienstleistung",
    competitors: "Commerzbank, internationale Großbanken.",
    opportunities: "Höhere Zinsen, stabileres Geschäft nach Umbau.",
    risks: "Konjunktur, Kreditausfälle, strenge Regulierung.",
    whyPriceMoves: "Zinsen, Konjunktur und Kreditrisiken wirken auf den Kurs.",
  },
  {
    ticker: "DHL",
    name: "DHL Group",
    whatDoes: "Die DHL Group (früher Deutsche Post) befördert Briefe und Pakete weltweit.",
    howEarns: "Durch Porto, Paket- und Logistikgebühren.",
    products: "Brief- und Paketdienst, Fracht, Logistik.",
    sector: "Industrie",
    competitors: "UPS, FedEx, lokale Postdienste.",
    opportunities: "Wachsender Onlinehandel, weltweite Logistik.",
    risks: "Konjunktur, Spritkosten, Wettbewerb im Paketmarkt.",
    whyPriceMoves: "Paketmengen und Logistiknachfrage beeinflussen den Kurs.",
  },
  {
    ticker: "IFX",
    name: "Infineon",
    whatDoes: "Infineon stellt Chips her, vor allem für Autos und Energietechnik.",
    howEarns: "Durch den Verkauf von Halbleitern an Industrie und Autohersteller.",
    products: "Chips für Autos, Strom-/Energietechnik, Sensoren.",
    sector: "Technologie",
    competitors: "STMicroelectronics, NXP, Texas Instruments.",
    opportunities: "E-Autos, erneuerbare Energie, mehr Elektronik im Alltag.",
    risks: "Schwankende Chip-Nachfrage, Konjunktur, Wettbewerb.",
    whyPriceMoves: "Nachfrage aus Auto- und Energiebranche bewegt den Kurs.",
  },
  {
    ticker: "BEI",
    name: "Beiersdorf",
    whatDoes: "Beiersdorf stellt Hautpflegeprodukte her.",
    howEarns: "Durch den Verkauf von Pflegeprodukten und Klebebändern (tesa).",
    products: "Nivea, Eucerin, tesa.",
    sector: "Konsumgüter",
    competitors: "L’Oréal, Procter & Gamble, Unilever.",
    opportunities: "Bekannte Marken, weltweite Nachfrage nach Pflege.",
    risks: "Rohstoffpreise, Wechselkurse, Wettbewerb.",
    whyPriceMoves: "Absatzmengen und Preise der Marken wirken auf den Kurs.",
  },
  {
    ticker: "HEN3",
    name: "Henkel",
    whatDoes: "Henkel stellt Wasch- und Reinigungsmittel sowie Klebstoffe her.",
    howEarns: "Durch den Verkauf von Konsumgütern und Industrieklebstoffen.",
    products: "Persil, Pritt, Klebstoffe für die Industrie.",
    sector: "Konsumgüter",
    competitors: "Procter & Gamble, Unilever, 3M.",
    opportunities: "Bekannte Marken, breites Industriegeschäft.",
    risks: "Rohstoffpreise, Konjunktur, Wettbewerb.",
    whyPriceMoves: "Absatz und Rohstoffkosten beeinflussen den Kurs.",
  },
  {
    ticker: "RWE",
    name: "RWE",
    whatDoes: "RWE erzeugt Strom, zunehmend aus Wind und Sonne.",
    howEarns: "Durch den Verkauf von Strom und den Betrieb von Kraftwerken.",
    products: "Strom aus Wind, Sonne, Gas; Energiehandel.",
    sector: "Versorger",
    competitors: "E.ON, Ørsted, EnBW.",
    opportunities: "Ausbau erneuerbarer Energien, Energiewende.",
    risks: "Schwankende Strompreise, hohe Investitionen, Politik.",
    whyPriceMoves: "Strompreise und der Ausbau erneuerbarer Energien wirken auf den Kurs.",
  },
  {
    ticker: "EOAN",
    name: "E.ON",
    whatDoes: "E.ON betreibt Stromnetze und beliefert Kunden mit Energie.",
    howEarns: "Durch den Betrieb von Netzen und den Verkauf von Strom und Gas.",
    products: "Stromnetze, Energieverträge für Haushalte und Firmen.",
    sector: "Versorger",
    competitors: "RWE, EnBW, regionale Versorger.",
    opportunities: "Ausbau und Modernisierung der Stromnetze.",
    risks: "Regulierung der Netze, hohe Investitionen, Politik.",
    whyPriceMoves: "Netzregulierung und Energiepreise beeinflussen den Kurs.",
  },
  {
    ticker: "NOVN",
    name: "Novartis",
    whatDoes: "Novartis ist ein Schweizer Pharmakonzern.",
    howEarns: "Durch den Verkauf verschreibungspflichtiger Medikamente.",
    products: "Medikamente gegen viele Krankheiten.",
    sector: "Gesundheit",
    competitors: "Roche, Pfizer, Johnson & Johnson.",
    opportunities: "Forschung an neuen Therapien, weltweite Nachfrage.",
    risks: "Patentabläufe, teure Forschung, Preisdruck.",
    whyPriceMoves: "Forschungserfolge und Patentabläufe bewegen den Kurs.",
  },
  {
    ticker: "ROG",
    name: "Roche",
    whatDoes: "Roche ist ein Schweizer Konzern für Medikamente und medizinische Tests.",
    howEarns: "Durch den Verkauf von Medikamenten und Diagnostik-Produkten.",
    products: "Medikamente, Labortests, Diagnostik.",
    sector: "Gesundheit",
    competitors: "Novartis, Pfizer, Johnson & Johnson.",
    opportunities: "Starke Forschung, wichtige Rolle in der Diagnostik.",
    risks: "Patentabläufe, teure Forschung, Preisdruck.",
    whyPriceMoves: "Forschungserfolge und die Nachfrage nach Tests wirken auf den Kurs.",
  },
  {
    ticker: "TTE",
    name: "TotalEnergies",
    whatDoes: "TotalEnergies ist ein französischer Energiekonzern für Öl, Gas und Strom.",
    howEarns: "Durch Förderung und Verkauf von Öl und Gas sowie zunehmend Strom.",
    products: "Kraftstoffe, Gas, Strom aus erneuerbaren Quellen.",
    sector: "Energie",
    competitors: "Shell, BP, Exxon Mobil.",
    opportunities: "Weltweiter Energiebedarf, Ausbau erneuerbarer Energien.",
    risks: "Schwankende Energiepreise, Klimaregeln, hohe Investitionen.",
    whyPriceMoves: "Öl-, Gas- und Strompreise bewegen den Kurs.",
  },
  {
    ticker: "ITX",
    name: "Inditex (Zara)",
    whatDoes: "Inditex betreibt Modeketten, am bekanntesten ist Zara.",
    howEarns: "Durch den Verkauf von Kleidung in Filialen und online.",
    products: "Modemarken wie Zara, Bershka, Pull&Bear.",
    sector: "Konsum",
    competitors: "H&M, Uniqlo, Onlinehändler.",
    opportunities: "Schnelle Mode, starke Filial- und Onlinekombination.",
    risks: "Modetrends, Konjunktur, Lieferketten.",
    whyPriceMoves: "Verkaufszahlen und Modetrends beeinflussen den Kurs.",
  },
  {
    ticker: "SHEL",
    name: "Shell",
    whatDoes: "Shell ist ein großer Energiekonzern für Öl, Gas und Tankstellen.",
    howEarns: "Durch Förderung, Verarbeitung und Verkauf von Öl- und Gasprodukten.",
    products: "Kraftstoffe, Gas, Tankstellen, Schmierstoffe.",
    sector: "Energie",
    competitors: "Exxon Mobil, BP, TotalEnergies.",
    opportunities: "Energiebedarf weltweit, Einstieg in saubere Energie.",
    risks: "Schwankende Energiepreise, Klimaregeln, hohe Investitionen.",
    whyPriceMoves: "Öl- und Gaspreise wirken stark auf den Kurs.",
  },
  {
    ticker: "ULVR",
    name: "Unilever",
    whatDoes: "Unilever stellt Lebensmittel, Pflege- und Haushaltsprodukte her.",
    howEarns: "Durch den Verkauf von Alltagsmarken in vielen Ländern.",
    products: "Pflege-, Wasch- und Lebensmittelmarken.",
    sector: "Konsumgüter",
    competitors: "Nestlé, Procter & Gamble, Henkel.",
    opportunities: "Viele bekannte Marken, weltweite Verbreitung.",
    risks: "Rohstoffpreise, Wechselkurse, Eigenmarken der Händler.",
    whyPriceMoves: "Absatzmengen und Preise der Marken bewegen den Kurs.",
  },
  {
    ticker: "AZN",
    name: "AstraZeneca",
    whatDoes: "AstraZeneca ist ein britisch-schwedischer Pharmakonzern.",
    howEarns: "Durch den Verkauf verschreibungspflichtiger Medikamente.",
    products: "Medikamente, u. a. gegen Krebs und Atemwegserkrankungen.",
    sector: "Gesundheit",
    competitors: "Roche, Novartis, Pfizer.",
    opportunities: "Starke Krebsforschung, weltweite Nachfrage.",
    risks: "Patentabläufe, teure Forschung, Preisdruck.",
    whyPriceMoves: "Forschungserfolge und Zulassungen bewegen den Kurs.",
  },
  {
    ticker: "OR",
    name: "L’Oréal",
    whatDoes: "L’Oréal ist der weltgrößte Hersteller von Kosmetik und Hautpflege.",
    howEarns: "Durch den Verkauf von Kosmetik- und Pflegeprodukten.",
    products: "Make-up, Hautpflege, Haarpflege, Parfüm.",
    sector: "Konsumgüter",
    competitors: "Beiersdorf, Procter & Gamble, Estée Lauder.",
    opportunities: "Starke Marken, weltweite Nachfrage, Onlineverkauf.",
    risks: "Konjunktur, Modetrends, Wechselkurse.",
    whyPriceMoves: "Absatz im Kosmetikmarkt und Trends wirken auf den Kurs.",
  },
  {
    ticker: "NOVO-B",
    name: "Novo Nordisk",
    whatDoes: "Novo Nordisk ist ein dänischer Pharmakonzern, bekannt für Mittel gegen Diabetes und Übergewicht.",
    howEarns: "Durch den Verkauf verschreibungspflichtiger Medikamente.",
    products: "Insulin und weitere Medikamente gegen Diabetes/Übergewicht.",
    sector: "Gesundheit",
    competitors: "Eli Lilly, Sanofi, andere Pharmafirmen.",
    opportunities: "Sehr große Nachfrage nach neuen Therapien.",
    risks: "Abhängigkeit von wenigen Medikamenten, Wettbewerb, Preisdruck.",
    whyPriceMoves: "Erfolg der wichtigen Medikamente beeinflusst den Kurs.",
  },
];

export const ETF_PROFILES: EtfProfile[] = [
  {
    ticker: "IWDA",
    name: "iShares Core MSCI World UCITS ETF (Acc)",
    isin: "IE00B4L5Y983",
    wkn: "A0RPWH",
    tracks: "Bildet den MSCI World ab – hunderte große und mittlere Firmen aus Industrieländern.",
    region: "Welt (Industrieländer)",
    sector: "Breit über alle Branchen gestreut",
    diversification: "Sehr breit: viele Länder und Branchen in einem Produkt.",
    costLogic: "Laufende Kosten (TER) pro Jahr, anteilig vom angelegten Wert.",
    risks: "Schwankungen des Weltmarkts; kein Schutz vor allgemeinen Kursrückgängen.",
  },
  {
    ticker: "CSPX",
    name: "iShares Core S&P 500 UCITS ETF (Acc)",
    isin: "IE00B5BMR087",
    wkn: "A0YEDG",
    tracks: "Bildet den S&P 500 ab – die 500 größten börsennotierten Firmen der USA.",
    region: "USA",
    sector: "Breit über US-Branchen gestreut",
    diversification: "Breit innerhalb der USA, aber auf ein Land konzentriert.",
    costLogic: "Laufende Kosten (TER) pro Jahr, anteilig vom angelegten Wert.",
    risks: "Konzentration auf die USA und den US-Dollar; Marktschwankungen.",
  },
  {
    ticker: "EIMI",
    name: "iShares Core MSCI EM IMI UCITS ETF (Acc)",
    isin: "IE00BKM4GZ66",
    wkn: "A111X9",
    tracks: "Bildet Schwellenländer ab (MSCI Emerging Markets IMI), z. B. China, Indien, Brasilien.",
    region: "Schwellenländer",
    sector: "Breit über Branchen der Schwellenländer gestreut",
    diversification: "Breit über viele Schwellenländer, aber schwankungsreicher.",
    costLogic: "Laufende Kosten (TER) pro Jahr, anteilig vom angelegten Wert.",
    risks: "Höhere Schwankungen, politische und Währungsrisiken.",
  },
];
