import type { CompanyProfile, EtfProfile } from "./schema.js";

// Redaktioneller Erstbestand. Wächst iterativ auf ~200 Unternehmen + 10 ETFs.
// Im Kindermodus werden KEINE frei generierten KI-Texte ausgespielt. ETFs sind neutrale
// Lernbeispiele, KEINE Kaufempfehlung. ISIN/WKN vor öffentlichem Start rechtlich verifizieren.

export const COMPANY_PROFILES: CompanyProfile[] = [
  {
    ticker: "AAPL",
    name: "Apple",
    whatDoes: "Apple entwickelt und verkauft Smartphones, Computer, Tablets, Uhren und Dienste.",
    howEarns: "Vor allem durch den Verkauf von Geräten wie dem iPhone und zusätzlich durch Dienste (z. B. App Store, iCloud).",
    products: "iPhone, iPad, Mac, Apple Watch, AirPods, App Store.",
    sector: "Technologie",
    competitors: "Samsung, Google, Microsoft.",
    opportunities: "Treue Kundschaft, starke Marke, wachsende Dienste-Umsätze.",
    risks: "Starke Abhängigkeit vom iPhone, Wettbewerb, Lieferketten in Asien.",
    whyPriceMoves: "Neue Produkte, Verkaufszahlen und die allgemeine Tech-Stimmung können den Kurs bewegen.",
  },
  {
    ticker: "SAP",
    name: "SAP",
    whatDoes: "SAP stellt Software her, mit der große Unternehmen ihre Abläufe (Einkauf, Personal, Finanzen) steuern.",
    howEarns: "Früher durch Software-Lizenzen, heute zunehmend durch Cloud-Abos (regelmäßige Mietzahlungen).",
    products: "Unternehmenssoftware (ERP), Cloud-Dienste.",
    sector: "Technologie",
    competitors: "Oracle, Microsoft, Salesforce.",
    opportunities: "Umstieg vieler Kunden in die Cloud, langfristige Verträge.",
    risks: "Harter Cloud-Wettbewerb, aufwendige Umstellungen bei Kunden.",
    whyPriceMoves: "Cloud-Wachstum, Quartalszahlen und Ausblicke beeinflussen den Kurs.",
  },
  {
    ticker: "SIE",
    name: "Siemens",
    whatDoes: "Siemens baut Technik für Industrie, Gebäude, Bahnverkehr und Stromnetze.",
    howEarns: "Durch Verkauf und Wartung von Maschinen, Anlagen, Zügen und Automatisierungstechnik.",
    products: "Industrieautomatisierung, Züge, Gebäudetechnik, Medizintechnik (Siemens Healthineers).",
    sector: "Industrie",
    competitors: "ABB, Schneider Electric, General Electric.",
    opportunities: "Automatisierung, Digitalisierung der Industrie, Bahn- und Energietrends.",
    risks: "Abhängigkeit von der Konjunktur, große langlaufende Projekte.",
    whyPriceMoves: "Auftragslage, Konjunktur und Großaufträge wirken auf den Kurs.",
  },
  {
    ticker: "NESN",
    name: "Nestlé",
    whatDoes: "Nestlé ist ein großer Lebensmittel- und Getränkekonzern aus der Schweiz.",
    howEarns: "Durch den Verkauf von Lebensmitteln und Getränken in vielen Ländern.",
    products: "Kaffee (Nescafé, Nespresso), Wasser, Süßwaren, Tiernahrung.",
    sector: "Konsumgüter",
    competitors: "Unilever, Mondelēz, Danone.",
    opportunities: "Bekannte Marken, weltweite Verbreitung, stabile Nachfrage nach Alltagsprodukten.",
    risks: "Rohstoffpreise, Wechselkurse, Diskussionen um Gesundheit und Nachhaltigkeit.",
    whyPriceMoves: "Absatzmengen, Preise und Wechselkurse können den Kurs bewegen.",
  },
  {
    ticker: "MSFT",
    name: "Microsoft",
    whatDoes: "Microsoft stellt Software und Cloud-Dienste für Menschen und Unternehmen her.",
    howEarns: "Durch Software (Windows, Office), Cloud (Azure) und Abos sowie Spiele (Xbox).",
    products: "Windows, Microsoft 365/Office, Azure, Xbox, Teams.",
    sector: "Technologie",
    competitors: "Google, Amazon, Apple.",
    opportunities: "Starkes Cloud-Geschäft, viele Firmenkunden, wachsende Abo-Umsätze.",
    risks: "Harter Cloud-Wettbewerb, Abhängigkeit von Firmenkunden, Regulierung.",
    whyPriceMoves: "Cloud-Wachstum, Quartalszahlen und die Tech-Stimmung bewegen den Kurs.",
  },
  {
    ticker: "AMZN",
    name: "Amazon",
    whatDoes: "Amazon betreibt einen riesigen Online-Handel und vermietet Cloud-Technik.",
    howEarns: "Durch Online-Verkäufe, Marktplatz-Gebühren, Abos (Prime) und die Cloud (AWS).",
    products: "Amazon-Onlineshop, Prime, AWS, Kindle, Alexa.",
    sector: "Konsum & Technologie",
    competitors: "Alibaba, Walmart, Microsoft (Cloud).",
    opportunities: "Wachstum im Online-Handel und in der Cloud, viele Prime-Mitglieder.",
    risks: "Niedrige Handelsmargen, hohe Kosten, Wettbewerb und Regulierung.",
    whyPriceMoves: "Wachstum von Handel und AWS sowie Gewinnentwicklung bewegen den Kurs.",
  },
  {
    ticker: "GOOGL",
    name: "Alphabet (Google)",
    whatDoes: "Alphabet ist das Mutterunternehmen von Google – Suche, YouTube, Android und mehr.",
    howEarns: "Vor allem durch Werbung in der Suche und auf YouTube, dazu Cloud-Dienste.",
    products: "Google-Suche, YouTube, Android, Chrome, Google Cloud.",
    sector: "Kommunikation/Technologie",
    competitors: "Microsoft, Meta, Amazon.",
    opportunities: "Sehr starke Werbeplattform, viele Nutzer, wachsende Cloud.",
    risks: "Abhängigkeit von Werbung, Datenschutz- und Wettbewerbsregeln.",
    whyPriceMoves: "Werbeeinnahmen, Nutzerzahlen und Regulierung bewegen den Kurs.",
  },
  {
    ticker: "NVDA",
    name: "Nvidia",
    whatDoes: "Nvidia entwickelt Chips für Grafik, Spiele und künstliche Intelligenz.",
    howEarns: "Durch den Verkauf von Grafik- und KI-Chips, vor allem an Rechenzentren.",
    products: "Grafikkarten (GeForce), KI-Beschleuniger für Rechenzentren.",
    sector: "Technologie",
    competitors: "AMD, Intel.",
    opportunities: "Großer Bedarf an KI-Chips, führende Technik.",
    risks: "Starke Schwankungen, Abhängigkeit vom KI-Boom, Wettbewerb, Lieferketten.",
    whyPriceMoves: "Nachfrage nach KI-Chips und Quartalszahlen bewegen den Kurs stark.",
  },
  {
    ticker: "TSLA",
    name: "Tesla",
    whatDoes: "Tesla baut Elektroautos und Speicher für Strom (Batterien).",
    howEarns: "Vor allem durch den Verkauf von Elektroautos, dazu Energie- und Softwareprodukte.",
    products: "Elektroautos (Model 3, Y), Batteriespeicher, Lade-Netzwerk.",
    sector: "Konsum/Auto",
    competitors: "Volkswagen, BYD, weitere Autohersteller.",
    opportunities: "Wachsender Markt für Elektroautos, bekannte Marke.",
    risks: "Starke Kursschwankungen, harter Wettbewerb, Abhängigkeit von wenigen Modellen.",
    whyPriceMoves: "Verkaufszahlen, Preise und Erwartungen bewegen den Kurs oft stark.",
  },
  {
    ticker: "VOW3",
    name: "Volkswagen",
    whatDoes: "Volkswagen ist ein großer Autohersteller mit vielen Marken.",
    howEarns: "Durch den Verkauf von Autos und Dienstleistungen rund ums Auto.",
    products: "VW, Audi, Porsche, Škoda, SEAT.",
    sector: "Konsum/Auto",
    competitors: "Toyota, Stellantis, Tesla.",
    opportunities: "Viele Marken, Umstieg auf Elektroautos, weltweite Präsenz.",
    risks: "Abhängigkeit von der Konjunktur, teurer Umbau zur E-Mobilität, Wettbewerb.",
    whyPriceMoves: "Absatzzahlen, Konjunktur und der E-Auto-Umstieg bewegen den Kurs.",
  },
  {
    ticker: "ALV",
    name: "Allianz",
    whatDoes: "Allianz ist ein großer Versicherungs- und Finanzkonzern.",
    howEarns: "Durch Versicherungsbeiträge und die Anlage/Verwaltung von Geld.",
    products: "Versicherungen (Auto, Leben, Sach), Vermögensverwaltung.",
    sector: "Finanzen",
    competitors: "AXA, Generali, Munich Re.",
    opportunities: "Stabile Beiträge, weltweites Geschäft, Vermögensverwaltung.",
    risks: "Große Schäden (z. B. Katastrophen), Zinsänderungen, Finanzmärkte.",
    whyPriceMoves: "Zinsen, Schadensereignisse und Finanzmärkte bewegen den Kurs.",
  },
  {
    ticker: "ADS",
    name: "Adidas",
    whatDoes: "Adidas stellt Sportschuhe, Kleidung und Ausrüstung her.",
    howEarns: "Durch den Verkauf von Sportartikeln über Handel und eigene Shops.",
    products: "Sportschuhe, Trikots, Sportkleidung.",
    sector: "Konsum",
    competitors: "Nike, Puma.",
    opportunities: "Starke Marke, weltweite Nachfrage, Sport-Trends.",
    risks: "Modetrends, Wettbewerb, Lieferketten und Wechselkurse.",
    whyPriceMoves: "Verkaufszahlen, Trends und Markenstärke bewegen den Kurs.",
  },
  {
    ticker: "MBG",
    name: "Mercedes-Benz Group",
    whatDoes: "Mercedes-Benz baut Autos und Transporter, vor allem in der Oberklasse.",
    howEarns: "Durch den Verkauf von Fahrzeugen und Finanzdienstleistungen.",
    products: "Pkw der Marke Mercedes-Benz, Vans, Finanzierung/Leasing.",
    sector: "Konsum/Auto",
    competitors: "BMW, Audi (VW), Tesla.",
    opportunities: "Starke Premium-Marke, Umstieg auf Elektro, weltweite Nachfrage.",
    risks: "Konjunktur, Wettbewerb, teurer E-Umbau, Wechselkurse.",
    whyPriceMoves: "Absatz in der Oberklasse, Konjunktur und E-Mobilität bewegen den Kurs.",
  },
  {
    ticker: "MC",
    name: "LVMH",
    whatDoes: "LVMH ist ein Luxuskonzern mit vielen bekannten Mode- und Marken.",
    howEarns: "Durch den Verkauf von Luxusgütern wie Mode, Taschen, Uhren und Parfüm.",
    products: "Louis Vuitton, Dior, Sephora, Champagner- und Uhrenmarken.",
    sector: "Konsum/Luxus",
    competitors: "Kering, Hermès, Richemont.",
    opportunities: "Starke Luxusmarken, treue Kundschaft, weltweites Wachstum.",
    risks: "Abhängigkeit von der Kauflaune Wohlhabender, Konjunktur, Wechselkurse.",
    whyPriceMoves: "Nachfrage nach Luxus, Konjunktur und Tourismus bewegen den Kurs.",
  },
];

export const ETF_PROFILES: EtfProfile[] = [
  {
    ticker: "IWDA",
    name: "iShares Core MSCI World UCITS ETF (Acc)",
    isin: "IE00B4L5Y983",
    wkn: "A0RPWH",
    tracks: "Bildet den MSCI World ab – hunderte große und mittlere Firmen aus Industrieländern.",
    region: "Welt (Industrieländer)",
    sector: "Breit über alle Branchen gestreut",
    diversification: "Sehr breit: viele Länder und Branchen in einem Produkt.",
    costLogic: "Laufende Kosten (TER) pro Jahr, anteilig vom angelegten Wert.",
    risks: "Schwankungen des Weltmarkts; kein Schutz vor allgemeinen Kursrückgängen.",
  },
  {
    ticker: "CSPX",
    name: "iShares Core S&P 500 UCITS ETF (Acc)",
    isin: "IE00B5BMR087",
    wkn: "A0YEDG",
    tracks: "Bildet den S&P 500 ab – die 500 größten börsennotierten Firmen der USA.",
    region: "USA",
    sector: "Breit über US-Branchen gestreut",
    diversification: "Breit innerhalb der USA, aber auf ein Land konzentriert.",
    costLogic: "Laufende Kosten (TER) pro Jahr, anteilig vom angelegten Wert.",
    risks: "Konzentration auf die USA und den US-Dollar; Marktschwankungen.",
  },
  {
    ticker: "EIMI",
    name: "iShares Core MSCI EM IMI UCITS ETF (Acc)",
    isin: "IE00BKM4GZ66",
    wkn: "A111X9",
    tracks: "Bildet Schwellenländer ab (MSCI Emerging Markets IMI), z. B. China, Indien, Brasilien.",
    region: "Schwellenländer",
    sector: "Breit über Branchen der Schwellenländer gestreut",
    diversification: "Breit über viele Schwellenländer, aber schwankungsreicher.",
    costLogic: "Laufende Kosten (TER) pro Jahr, anteilig vom angelegten Wert.",
    risks: "Höhere Schwankungen, politische und Währungsrisiken.",
  },
];
